DPR-DataMigrationEngine/Controllers/BlockController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.BulkUploadManagerManager;
using DPR_DataMigrationEngine.EF.CustomizedModels;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;
using Block = DPR_DataMigrationEngine.EF.Models.Block;

namespace DPR_DataMigrationEngine.Controllers
{
   [CustomAuthorize(Roles = "Admin,Super_Admin")]
    public class BlockController : Controller
    {
        public BlockController()
		{
			 ViewBag.LoadStatus = "0";
		}

       public ActionResult Blocks()
        {
            try
            {
                var leaseType = GetLeaseTypes();

                if (!leaseType.Any())
                {
                    return RedirectToAction("LeaseTypes", "LeaseType");
                }
              

                var companies = GetCompanies();

                if (!companies.Any())
                {
                    return RedirectToAction("Companies", "Company");
                }

                var blockTypes = GetBlockTypes();

                var blockList = GetBlocks();

                if (!blockList.Any())
                {
                    ViewBag.Edit = 1;
                    ViewBag.Title = "Block SetUp";
                    return View(new BlockViewModel
                    {
                        BlockTypes = blockTypes,
                        Blocks = new List<Block>(),
                        LeaseTypes = leaseType,
                        Companies = companies
                    });
                }
              
                ViewBag.Title = "Manage blocks";
                return View(new BlockViewModel { BlockTypes = blockTypes, Blocks = blockList, LeaseTypes = leaseType, Companies = GetCompanies()});
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                ViewBag.ErrorCode = -1;
                ViewBag.ErrorMessage = "Block list could not be retrieved. Please try again later.";
                ViewBag.Title = "Block SetUp";
                return View(new BlockViewModel { BlockTypes = GetBlockTypes(), Blocks = new List<Block>(), LeaseTypes = GetLeaseTypes(), Companies = GetCompanies() });
            }
        }

        private List<BlockType> GetBlockTypes()
       {
           return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
       }

        private List<Block> GetBlocks()
        {
            return new BlockServices().GetAllOrderedBlocks() ?? new List<Block>();
        }

        private List<LeaseType> GetLeaseTypes()
        {
            return new LeaseTypeServices().GetAllOrderedLeaseTypes() ?? new List<LeaseType>();
        }

        private List<Field> GetFields()
        {
            return new FieldServices().GetFields() ?? new List<Field>();
        }

        private List<Company> GetCompanies()
        {
            return new CompanyServices().GetAllOrderedCompanies() ?? new List<Company>();
        }

        [HttpPost]
        public ActionResult AddBlock(Block block)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (!ModelState.IsValid)
                {
                    block.Error = "Please supply all required fields and try again";
                    block.ErrorCode = -1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                var wx = ValidateControl(block);

                if (wx.Code < 1)
                {
                    block.Error = wx.Error;
                    block.ErrorCode = -1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }
               
                var k = new BlockServices().AddBlockCheckDuplicate(block);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        block.Error = "Block  already exists";
                        block.ErrorCode = -3;
                        return Json(block, JsonRequestBehavior.AllowGet);
                    }

                    block.Error = "Process Failed! Please contact the Admin or try again later";
                    block.ErrorCode = 0;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                block.Error = "Record was added successfully";
                block.ErrorCode = 1;
                block.BlockId = k;
                return Json(block, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                block.Error = "An unknown error was encountered. Request could not be serviced. Please try again later.";
                block.ErrorCode = 0;
                return Json(block, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditBlock(Block block)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (Session["_block"] == null)
                {
                    block.Error = "Session has expired";
                    block.ErrorCode = 0;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                var oldBlock = Session["_block"] as Block;

                if (oldBlock == null || oldBlock.BlockId < 1)
                {
                    block.Error = "Session has expired";
                    block.ErrorCode = 0;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                if (!ModelState.IsValid)
                {
                    block.Error = "Please supply all required fields and try again";
                    block.ErrorCode = -1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                var wx = ValidateControl(block);

                if (wx.Code < 1)
                {
                    block.Error = wx.Error;
                    block.ErrorCode = -1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                oldBlock.Name = block.Name;
                oldBlock.CompanyId = block.CompanyId;
                oldBlock.LeaseTypeId = block.LeaseTypeId;
                oldBlock.YearOfAward = block.YearOfAward;
                oldBlock.Area = block.Area;
                oldBlock.BlockTypeId = block.BlockTypeId;
                
                var k = new BlockServices().UpdateBlockCheckDuplicate(oldBlock);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        block.Error = "Block  already exists";
                        block.ErrorCode = 0;
                        return Json(block, JsonRequestBehavior.AllowGet);
                    }

                    block.Error = "Process Failed! Please contact the Admin or try again later";
                    block.ErrorCode = 0;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }
                
                    block.Error = "Block  Information was successfully updated";
                    block.ErrorCode = 1;
                    return Json(block, JsonRequestBehavior.AllowGet);
            }
            catch (Exception )
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                block.Error = "An unknown error was encountered. Request could not be serviced. Please try again later.";
                block.ErrorCode = 0;
                return Json(block, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ActionName("DeleteBlock")]
        public ActionResult DeleteBlock(int id)
        {
            var block = new Block();

            try
            {
                if (id < 1)
                {
                    block.Error = "Invalid Selection";
                    block.ErrorCode = 0;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }
                if (new BlockServices().DeleteBlockCheckReferences(id))
                {
                    block.Error = "Block  Information was successfully deleted.";
                    block.ErrorCode = 1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                block.Error = "Process Failed! Please try again later";
                block.ErrorCode = 0;
                return Json(block, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                block.Error = "An unknown error was encountered. Please contact the Administrator or try again later.";
                block.ErrorCode = 0;
                return Json(block, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditBlock(int id)
        {
            var block = new Block();
            try
            {
                if (id < 1)
                {
                    block.Error = "Invalid Selection!";
                    block.ErrorCode = -1;
                    return Json(block, JsonRequestBehavior.AllowGet);
                }

                var myViewObj = new BlockServices().GetBlock(id);

                if (myViewObj == null || myViewObj.BlockId < 1)
                {
                    block.Error = "Block  Information could not be retrieved.";
                    block.ErrorCode = -1;

DPR-DataMigrationEngine/Controllers/Reports/DynamicReports/FieldReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.Reports.DynamicReports
{
    [CustomAuthorize]
    public class FieldReportController : Controller
    {
       public ActionResult DynamicReports()
        {
            return View(new FieldViewModel
            {
                Terrains = GetTerrains(),
                Zones = GetZones(),
                Companies = GetCompanyies(), 
                FieldQueries = GetFieldQueries() });
        }

       private List<Terrain> GetTerrains()
       {
           return new TerrainServices().GetAllOrderedTerrains() ?? new List<Terrain>();
       }
        private List<BlockType> GetBlockTypes()
        {
            return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
        }
        private List<Block> GetBlocks()
        {
            return new BlockServices().GetAllOrderedBlocks() ?? new List<Block>();
        }
        private List<Company> GetCompanyies()
        {
            return new CompanyServices().GetCompaniesWithBlocks() ?? new List<Company>();
        }
        private List<Zone> GetZones()
        {
            return new ZoneServices().GetAllOrderedZones() ?? new List<Zone>();
        }
        public ActionResult GetFields(FieldQuery queryBuilder)
        {
            if (queryBuilder == null)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            
            if (queryBuilder.TerrainId < 1 && queryBuilder.CompanyId < 1 && queryBuilder.ZoneId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(queryBuilder) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            Session["_successfulFieldQuery"] = queryBuilder;
            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        public ActionResult GetFields2(int queryId)
        {
            if (queryId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var query = new FieldQueryBuilderServices().GetFieldQuery(queryId);

            if (query == null || query.FieldQueryId < 1)
            {

                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(query) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        [HttpPost]
        public ActionResult SaveSuccessfulQuery(string queryName)
        {
            var genVal = new GenericValidator();

            try
            {
                if (string.IsNullOrEmpty(queryName))
                {
                    genVal.Error = "Please supply all required fields and try again";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                queryBuilder.FieldQueryName = queryName.Trim();

                var k = new FieldQueryBuilderServices().AddFieldQueryCheckDuplicate(queryBuilder);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        genVal.Error = "Query already exists";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }
                    if (k == -4)
                    {
                        genVal.Error = "Query Name already exists. Please provide a different one";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }

                    genVal.Error = "Process Failed! Please contact the Admin or try again later";
                    genVal.Code = 0;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                genVal.Error = "Query was successfully saved";
                genVal.Code = (int) k;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                genVal.Error = "An unknown error was encountered. Query could not be saved. Please try again.";
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult IsFieldQueryExisting()
        {
            var genVal = new GenericValidator();

            try
            {
                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var k = new FieldQueryBuilderServices().IsFieldQueryExisting(queryBuilder);
                if (k)
                {
                    genVal.Code = 5;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }


                if (Roles.IsUserInRole("Admin"))
                {
                    genVal.Code = -5;
                }
                else
                {
                    genVal.Code = -2;
                }
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        private List<FieldQuery> GetFieldQueries()
        {
            var previousQueries = new FieldQueryBuilderServices().GetAllOrderedFieldQueries() ?? new List<FieldQuery>();

            if (!previousQueries.Any())
            {
                return new List<FieldQuery>();
            }
            return previousQueries;
        }
    }
}

DPR-DataMigrationEngine/Views/Block/BlockUpload.cshtml
@{
    ViewBag.Title = "Block Bulk Upload";
}

<style type="text/css">
    a#ancClose:link, a#ancClose:visited, a#ancClose:active, a#ancClose:hover {
        text-decoration: none;
        background: url(/Images/cancel.png) 80px no-repeat green;
        -ms-background-size: 18px 18px;
        background-size: 18px 18px;
        color: #FFF;
        cursor: pointer;
        border: none;
    }
</style>



@{

    if (ViewBag.ErrorCode < 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: black;"> @td </label>

    }

    if (ViewBag.ErrorCode > 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: green;">@td</label>

    }
}




<table style="width: 65%">
    <tr>
        <td style="width: 90%">
            <form class="fsEdit" method="POST" action="@Url.Action("BlockUpload", "Block")" enctype="multipart/form-data" id="frmWellProcessDocs" style="width: 100%">
                <span class="legend22" style="width: 100%">Block Bulk Upload</span>
                @*@Html.AntiForgeryToken()*@
                @Html.ValidationSummary(true)
                <table style="width: 100%; background: whitesmoke; border: none; margin-top:0">
                    <tr>
                        <td colspan="2">
                            <div style="width: 100%; font-weight: bold; font-size: 8pt; display: none; visibility: visible" class="error label" id="brEdErrorBulk"></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="form-group">
                            <div>&nbsp;</div>
                            <br /><i style="width: auto">Select Excel Data File *</i>
                            <input id="fldDocument" type="file" name="file" style="width: 100%" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div>&nbsp;</div>
                            <div style="width: 100%;">
                                <div style="text-align: center; float: right; margin-top: 1%">
                                    <a id="ancClose" style="border: none; float:right; width: 110px" class="btn btnClose large" href="/Block/Blocks"> Close</a> &nbsp; &nbsp; &nbsp;
                                </div>
                                <input type="submit" id="btnProcessBulkUpload" class="btn btnUpload large" style=" border: none; float: right; width: 110px" value="Upload" onclick="return valIdateTemplatewx();" />
                            </div>
                        </td>
                    </tr>
                </table>
            </form>
        </td>
        <td style="width:10%; padding-right: 8px; vertical-align: top; text-align: center">
            <div style="text-align: center; margin-top: 20%">
                <a title="Download Block Bulk Upload Template" style="cursor:pointer; text-decoration: none" href="@("/Company/DownloadContentFromFolder?path=" + "~/BulkTemplate/BlockBulkTemplate.xlsx")" id="dnBulkTemplate"><img src="/Images/downloadExcel.png" alt="download Block Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>
        </td>
    </tr>
</table>

<script type="text/javascript">

    function valIdateTemplatewx() {
        if ($('#fldDocument').val().trim().length < 1) {
            alert("Please Select an Excel file to upload!");
            $('#fldDocument').val('');
            return false;
        }
        return true;
    }

</script>

DPR-DataMigrationEngine/Views/Block/Report.cshtml
@using DPR_DataMigrationEngine.HTMLExtensionHelpers
@model List<DPR_DataMigrationEngine.EF.Models.Block>

<table style="width: 100%">
    <tr>
        <td style="width: 90%"></td>
        <td style="padding-right:0; width: 5%">
            <div>&nbsp;</div>
            <a onclick="tableToExcel('tblBlockRep', 'Block Report')"><img src="/Images/export2Excel2.jpg" style="float: right; margin-right: -2%; cursor: pointer" title="Export to Excel" /></a>
        </td>
        <td style="padding-right:0;width: 5%">
            <div>&nbsp;</div>
            <img src="/Images/printer-24_opt.png" style="float: left; cursor: pointer" title="Print Report" onclick="printBlockReport()" />
        </td>
    </tr>
</table>
<fieldset id="fsBlockList" style="background: whitesmoke; width: 100%" class="allcontent">
    <legend class="customlegend22" id="lgHeader">Block Report</legend>
   
    <table id="tblBlockRep" style="width: 100%" class="fils-border newTable">
        <tr class="customGridHeader">
            <th style="width: 5%; text-align: center">
                S/N
            </th>
            <th style="width: 15%; text-align: left">
                Block
            </th>
            <th style="width: 15%; text-align: left">
                Block Type
            </th>
            <th style="width: 15%; text-align: left">
                Lease Type
            </th>
            <th style="width: 12%; text-align: left">
                Year Of Award
            </th>
            <th style="width: 15%; text-align: left">
                Company
            </th>
            <th style="width: 15%; text-align: left">
                Area(Kmsq)
            </th>
        </tr>
        @{
            for (var i = 0; i < Model.Count(); i++)
            {
                var zxz = Model[i];
                <tr id="tr@(zxz.BlockId)" class="xtcR" style="color: black;">
                    <td style="width: 5%; text-align: center" class="xtc">
                        @(i + 1)
                    </td>
                    <td style="width: 15%; text-align: left" id="tdName">
                        @zxz.Name
                    </td>
                    <td style="width: 15%; text-align: left" id="tdBlockTypeName">
                        @zxz.BlockType.Name
                    </td>
                    <td style="width: 15%; text-align: left" id="tdLeaseType">
                        @zxz.LeaseType.Name
                    </td>
                    <td style="width: 12%; text-align: left" id="tdAwardYear">
                        @zxz.YearOfAward
                    </td>
                    <td style="width: 15%; text-align: left" id="tdCompany">
                        @zxz.Company.Name
                    </td>
                    <td style="width: 15%; text-align: left" id="tdArea">
                        @zxz.Area
                    </td>
                </tr>
            }
        }
    </table>
</fieldset>

<script type="text/javascript">
    function printBlockReport() {
        if ($('#tblBlockRep').html() == null) {

            alert('Nothing to Print');
            return;
        }
        printReportData('fsBlockList');
    }

</script>