DPR-DataMigrationEngine/Controllers/ProductionMgt/ProductionController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DPR_DataMigrationEngine.BulkUploadManagerManager;
using DPR_DataMigrationEngine.EF.CustomizedModels;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.ProductionMgt
{
    [CustomAuthorize]
    public class ProductionController : Controller   
    {
        public ProductionController()
		{
			 ViewBag.LoadStatus = "0";
		}
        private const int ItemsPerPage = 50;
        private const int PageNumber = 1;

        [CustomAuthorize(Roles = "Data_Entry,Super_Admin")]
        public ActionResult Productions()
        {
            try
            {
                var productList = GetProducts();

                if (!productList.Any())
                {
                    ViewBag.Edit = 0;
                    ViewBag.Title = "Product Set Up";
                    return RedirectToAction("Products", "Product");
                }

                var fieldList = GetFields();

                if (!fieldList.Any())
                {
                    return RedirectToAction("Fields", "Field");
                }

                var yearList = GetYears();
                var monthList = GetMonths();
                int dataCount;
                var productionList = GetProductions(ItemsPerPage, PageNumber, out dataCount);
                if (!productionList.Any())
                {
                    ViewBag.ErrorCode = 0;
                    ViewBag.Title = "Production Set Up";
                    return View(new ProductionViewModel
                    {
                        Products = GetProducts(),
                        Fields = GetFields(),
                        YearList = yearList,
                        MonthList = monthList,
                        Productions = GetProductions(ItemsPerPage, PageNumber, out dataCount)
                    });

                }

                ViewBag.ErrorCode = 0;
                ViewBag.Title = "Manage Productions";
                Session["_prodPage"] = 1;
                return View(new ProductionViewModel { Products = GetProducts(), Fields = GetFields(), YearList = yearList, MonthList = monthList, Productions = GetProductions( ItemsPerPage, PageNumber, out dataCount) });
            }
            catch (Exception ex)
            {
               ViewBag.ErrorCode = -1;
                ViewBag.ErrorMessage = "Production List is could not be retrieved. Please try again later.";
                ViewBag.Title = "Production Set Up";
                var yearList = GetYears();
                var monthList = GetMonths();
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return View(new ProductionViewModel { Products = GetProducts(), Fields = GetFields(), YearList = yearList, MonthList = monthList, Productions = new List<Production>()});

            }
        }

        [CustomAuthorize(Roles = "Data_Entry,Super_Admin")]
        public ActionResult DataTemplates()
        {
            return View();
        }

        private List<BlockType> GetBlockTypes()
        {
            return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
        }
       private List<Terrain> GetTerrains()
        {
            return new TerrainServices().GetAllOrderedTerrains() ?? new List<Terrain>();
        }
        private List<Company> GetCompanies()
        {
            return new CompanyServices().GetAllOrderedCompanies() ?? new List<Company>();
        }
        private List<Product> GetProducts()
        {
            try
            {
                var productList = new ProductServices().GetAllOrderedProducts() ?? new List<Product>();

                if (!productList.Any())
                {
                    return new List<Product>();
                }

                return productList;
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return new List<Product>();
            }
        }
        private List<Production> GetProductions(int itemsPerPage, int pageNumber, out int dataCount)
        {
            try
            {
                var productionList = new ProductionServices().GetAllOrderedProductions(itemsPerPage, pageNumber, out dataCount);
                ViewBag.PrDataCount = dataCount.ToString(CultureInfo.InvariantCulture);

                var totalPages = dataCount / itemsPerPage;

                // Counting the last page
                if (dataCount % itemsPerPage != 0)
                {
                    totalPages++;
                }

                ViewBag.PrTotalPages = totalPages;
                ViewBag.PrPage = pageNumber;
                if (!productionList.Any())
                {
                    return new List<Production>();
                }
                productionList.ForEach(m =>
                {
                    m.FieldName = m.Field.Name;
                    m.ProductName = m.Product.Name;
                    m.Quantity = Convert.ToDecimal(m.Quantity).ToString("#,##0");
                    m.MonthName = Enum.GetName(typeof(MonthList), m.Month);
                });
                return productionList;
            }
            catch (Exception ex)
            {
                dataCount = 0;
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return new List<Production>();
            }
        }
        private List<Field> GetFields()
        {
            try
            {
                var fieldList = new FieldServices().GetFields() ?? new List<Field>();

                if (!fieldList.Any())
                {
                    return new List<Field>();
                }

                return fieldList;
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return new List<Field>();
            }
        }
        public ActionResult GetMoreWellCompletions()
        {
            int currentPage;

            var o = Session["_prodPage"];
            if (o != null)
            {
                var page = (int)o;
                if (page < 1)
                {
                    currentPage = 1;
                }

                else
                {
                    currentPage = page + 1;
                }
            }
            else
            {
                currentPage = 1;
            }

            var wellList = GetWellComletionObjects(50, currentPage);

            if (!wellList.Any())
            {
                return Json(new List<ProductionObject>(), JsonRequestBehavior.AllowGet);
            }
            Session["_prodPage"] = currentPage;
            return Json(wellList, JsonRequestBehavior.AllowGet);
        }
        private List<ProductionObject> GetWellComletionObjects(int itemsPerPage, int pageNumber)
        {
            try
            {
                var wellCompletions = new ProductionServices().GetMoreProductionObjects(itemsPerPage, pageNumber);

                if (!wellCompletions.Any())
                {

                    return new List<ProductionObject>();
                }

                return wellCompletions;
            }
            catch (Exception ex)
            {
                return new List<ProductionObject>();
            }
        }
        public ActionResult GetProductionsByField(int fieldId)
        {
            try
            {
                if (fieldId < 1)
                {
                    return Json(new List<Field>(), JsonRequestBehavior.AllowGet);
                }

                var productionList = new ProductionServices().GetAllOrderedProductionsByFieldId(fieldId);

                if (!productionList.Any())
                {
                    return Json(new List<Production>(), JsonRequestBehavior.AllowGet);
                }

                return Json(productionList, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return Json(new List<Production>(), JsonRequestBehavior.AllowGet);
            }
        }

        [CustomAuthorize(Roles = "Data_Entry,Super_Admin")]
        [HttpPost]
        public ActionResult AddProduction(Production production)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (!ModelState.IsValid)
                {
                    production.Error = "Please supply all required fields and try again";
                    production.ErrorCode = -1;
                    return Json(production, JsonRequestBehavior.AllowGet);
                }

                var wx = ValidateControl(production);
                if (wx.Code < 1)
                {
                    production.Error = wx.Error;
                    production.ErrorCode = -1;
                    return Json(production, JsonRequestBehavior.AllowGet);
                }
                var ty = production.Quantity.Replace(",", "").Replace(" ", "");
                production.Quantity = ty;
                production.Year = production.ProductionDate.Year;
                production.Month = production.ProductionDate.Month;
                production.MonthName = Enum.GetName(typeof(MonthList), production.Month);
                var k = new ProductionServices().AddProduction(production);
                if (k < 1)
                {
                   production.Error = "Process Failed! Please contact the Admin or try again later";
                    production.ErrorCode = 0;

DPR-DataMigrationEngine/Controllers/Reports/DynamicReports/FieldReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.Reports.DynamicReports
{
    [CustomAuthorize]
    public class FieldReportController : Controller
    {
       public ActionResult DynamicReports()
        {
            return View(new FieldViewModel
            {
                Terrains = GetTerrains(),
                Zones = GetZones(),
                Companies = GetCompanyies(), 
                FieldQueries = GetFieldQueries() });
        }

       private List<Terrain> GetTerrains()
       {
           return new TerrainServices().GetAllOrderedTerrains() ?? new List<Terrain>();
       }
        private List<BlockType> GetBlockTypes()
        {
            return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
        }
        private List<Block> GetBlocks()
        {
            return new BlockServices().GetAllOrderedBlocks() ?? new List<Block>();
        }
        private List<Company> GetCompanyies()
        {
            return new CompanyServices().GetCompaniesWithBlocks() ?? new List<Company>();
        }
        private List<Zone> GetZones()
        {
            return new ZoneServices().GetAllOrderedZones() ?? new List<Zone>();
        }
        public ActionResult GetFields(FieldQuery queryBuilder)
        {
            if (queryBuilder == null)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            
            if (queryBuilder.TerrainId < 1 && queryBuilder.CompanyId < 1 && queryBuilder.ZoneId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(queryBuilder) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            Session["_successfulFieldQuery"] = queryBuilder;
            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        public ActionResult GetFields2(int queryId)
        {
            if (queryId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var query = new FieldQueryBuilderServices().GetFieldQuery(queryId);

            if (query == null || query.FieldQueryId < 1)
            {

                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(query) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        [HttpPost]
        public ActionResult SaveSuccessfulQuery(string queryName)
        {
            var genVal = new GenericValidator();

            try
            {
                if (string.IsNullOrEmpty(queryName))
                {
                    genVal.Error = "Please supply all required fields and try again";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                queryBuilder.FieldQueryName = queryName.Trim();

                var k = new FieldQueryBuilderServices().AddFieldQueryCheckDuplicate(queryBuilder);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        genVal.Error = "Query already exists";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }
                    if (k == -4)
                    {
                        genVal.Error = "Query Name already exists. Please provide a different one";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }

                    genVal.Error = "Process Failed! Please contact the Admin or try again later";
                    genVal.Code = 0;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                genVal.Error = "Query was successfully saved";
                genVal.Code = (int) k;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                genVal.Error = "An unknown error was encountered. Query could not be saved. Please try again.";
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult IsFieldQueryExisting()
        {
            var genVal = new GenericValidator();

            try
            {
                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var k = new FieldQueryBuilderServices().IsFieldQueryExisting(queryBuilder);
                if (k)
                {
                    genVal.Code = 5;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }


                if (Roles.IsUserInRole("Admin"))
                {
                    genVal.Code = -5;
                }
                else
                {
                    genVal.Code = -2;
                }
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        private List<FieldQuery> GetFieldQueries()
        {
            var previousQueries = new FieldQueryBuilderServices().GetAllOrderedFieldQueries() ?? new List<FieldQuery>();

            if (!previousQueries.Any())
            {
                return new List<FieldQuery>();
            }
            return previousQueries;
        }
    }
}

DPR-DataMigrationEngine/Views/Production/DataTemplates.cshtml
@{
    ViewBag.Title = "Data Templates";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<table style="width: 50%">
    <tr>
        <td colspan="4">
            <span class="legend2x" style="width: 100%">Bulk Upload Templates - Data Admin </span>
        </td>
    </tr>
    <tr>
        <td colspan="4"><div>&nbsp;</div></td>
    </tr>
    <tr>
        <td style="width:10%; padding-right: 8px; vertical-align: top; text-align: center">
            <label class="control-label" style="font-weight: normal; font-size: 9pt">Production Template</label>
            <div style="text-align: center; margin-top: 20%">
                <a title="Download Production Bulk Upload Template" style="cursor:pointer" href="@("/Production/DownloadContentFromFolder?path=" + "~/BulkTemplate/ProductionTemplate.xlsx")"><img src="/Images/downloadExcel.png" alt="download Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>
        </td>
        <td style="width:25%; padding-right: 8px; vertical-align: top; text-align: center">
            <label class="control-label" style="font-weight: normal; font-size: 9pt">Well Workover Template</label>
            <div style="text-align: center; margin-top: 20%">
                <a title="Download Bulk Upload Template" id="dnTx" style="cursor:pointer" href="@("/WellWorkOver/DownloadContentFromFolder?path=" + "~/BulkTemplate/WellWorkOverTemplate.xlsx")"><img src="/Images/downloadExcel.png" alt="download Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>
        </td>
        <td style="width:25%; padding-right: 8px; vertical-align: top; text-align: center">
            <label class="control-label" style="font-weight: normal; font-size: 9pt">Well Completion Template</label>
            <table style="width: 100%">
                <tr>
                    <td>
                        <div style="text-align: center; float: right">
                            <a title="Download Single Completion Bulk Upload Template" style="cursor: pointer; text-decoration: none" href="@("/Company/DownloadContentFromFolder?path=" + "~/BulkTemplate/SingleIntervalWellCompletionTemplate.xlsx")" id="dnBulkTemplate"><img src="/Images/downloadExcel.png" alt="download Single Completion Bulk Upload Template" style="width: 40px; height: 40px" />Single Completion</a>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div style="text-align: center; margin-top: 20%">
                            <a title="Download  Dual Completion Bulk Upload Template" style="cursor:pointer; text-decoration: none" href="@("/Company/DownloadContentFromFolder?path=" + "~/BulkTemplate/DualIntervalWellCompletionTemplate.xlsx")" id="dnBulkTemplate"><img src="/Images/downloadExcel.png" alt="download Dual Completion Bulk Upload Template" style="width: 40px; height: 40px" />Dual Completion</a>
                        </div>
                    </td>
                </tr>
            </table>>
        </td>
        <td style="width:25%; padding-right: 8px; vertical-align: top; text-align: center">
            <label class="control-label" style="font-weight: normal; font-size: 9pt">Well Template</label>
            <div style="text-align: center; margin-top: 20%">
                <a title="Download Well Bulk Upload Template" style="cursor:pointer" href="@("/Well/DownloadContentFromFolder?path=" + "~/BulkTemplate/WellTemplate.xlsx")"><img src="/Images/downloadExcel.png" alt="download Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>
        </td>
    </tr>
</table>

DPR-DataMigrationEngine/Views/Production/ProductionUpload.cshtml
@{
    ViewBag.Title = "Production Bulk Upload";
}


<style type="text/css">
    a#ancClose:link, a#ancClose:visited, a#ancClose:active, a#ancClose:hover {
        text-decoration: none;
        background: url(/Images/cancel.png) 80px no-repeat green;
        -ms-background-size: 18px 18px;
        background-size: 18px 18px;
        color: #FFF;
        cursor: pointer;
        border: none;
    }
</style>

@{

    if (ViewBag.ErrorCode < 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: black;"> @td </label>

    }

    if (ViewBag.ErrorCode > 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: green;">@td</label>

    }
}


<table style="width: 60%">
    <tr>
        <td style="width: 90%">
            <form class="fsEdit" style="width: 100%" method="POST" action="@Url.Action("ProductionUpload", "Production")" enctype="multipart/form-data" id="frmProcessProductionDocs">
                <span class="legend22" style="width: 100%">Production Bulk Upload</span>
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <table style="width: 100%; background: whitesmoke; border: none;margin-top:0">
                    <tr>
                        <td colspan="2">
                            <div style="width: 100%; font-weight: bold; font-size: 8pt; display: none; visibility: visible" class="error label" id="brEdErrorProductionBulk"></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="form-group">
                            <br /><i style="width: auto">Select Excel Data File *</i>
                            <input id="fdProductionTemplate" type="file" name="file" style="width: 98%; margin-left: 1%" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div>&nbsp;</div>
                            <div style="width: 100%; margin-left: 0">
                                <div style="text-align: center; float: right; margin-top: 1%">
                                    <a id="ancClose" style="border: none; float:right; width: 110px" class="btn btnClose large" href="/Production/Productions">Close</a>&nbsp; &nbsp; &nbsp;
                                </div>
                                    <input type="submit" id="btnProcessBulkProduction" class="btn btnUpload large" style=" border: none; float: right; width: 110px" value="Upload" onclick="return valIdateProductionTemplate();" />
                                </div>
                        </td>
                    </tr>
                </table>
            </form> 
        </td>
        <td style="width:10%; padding-right: 8px; vertical-align: top">
            <div style="text-align: center; float: right">
                <a title="Download Bulk Upload Template" style="cursor:pointer" href="@("/Production/DownloadContentFromFolder?path=" + "~/BulkTemplate/ProductionTemplate.xlsx")"><img src="/Images/downloadExcel.png" alt="download Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>

        </td> 
    </tr>
</table>