DPR-DataMigrationEngine/Controllers/Reports/DynamicReports/FieldReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.Reports.DynamicReports
{
    [CustomAuthorize]
    public class FieldReportController : Controller
    {
       public ActionResult DynamicReports()
        {
            return View(new FieldViewModel
            {
                Terrains = GetTerrains(),
                Zones = GetZones(),
                Companies = GetCompanyies(), 
                FieldQueries = GetFieldQueries() });
        }

       private List<Terrain> GetTerrains()
       {
           return new TerrainServices().GetAllOrderedTerrains() ?? new List<Terrain>();
       }
        private List<BlockType> GetBlockTypes()
        {
            return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
        }
        private List<Block> GetBlocks()
        {
            return new BlockServices().GetAllOrderedBlocks() ?? new List<Block>();
        }
        private List<Company> GetCompanyies()
        {
            return new CompanyServices().GetCompaniesWithBlocks() ?? new List<Company>();
        }
        private List<Zone> GetZones()
        {
            return new ZoneServices().GetAllOrderedZones() ?? new List<Zone>();
        }
        public ActionResult GetFields(FieldQuery queryBuilder)
        {
            if (queryBuilder == null)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            
            if (queryBuilder.TerrainId < 1 && queryBuilder.CompanyId < 1 && queryBuilder.ZoneId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(queryBuilder) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            Session["_successfulFieldQuery"] = queryBuilder;
            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        public ActionResult GetFields2(int queryId)
        {
            if (queryId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var query = new FieldQueryBuilderServices().GetFieldQuery(queryId);

            if (query == null || query.FieldQueryId < 1)
            {

                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(query) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        [HttpPost]
        public ActionResult SaveSuccessfulQuery(string queryName)
        {
            var genVal = new GenericValidator();

            try
            {
                if (string.IsNullOrEmpty(queryName))
                {
                    genVal.Error = "Please supply all required fields and try again";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                queryBuilder.FieldQueryName = queryName.Trim();

                var k = new FieldQueryBuilderServices().AddFieldQueryCheckDuplicate(queryBuilder);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        genVal.Error = "Query already exists";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }
                    if (k == -4)
                    {
                        genVal.Error = "Query Name already exists. Please provide a different one";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }

                    genVal.Error = "Process Failed! Please contact the Admin or try again later";
                    genVal.Code = 0;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                genVal.Error = "Query was successfully saved";
                genVal.Code = (int) k;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                genVal.Error = "An unknown error was encountered. Query could not be saved. Please try again.";
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult IsFieldQueryExisting()
        {
            var genVal = new GenericValidator();

            try
            {
                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var k = new FieldQueryBuilderServices().IsFieldQueryExisting(queryBuilder);
                if (k)
                {
                    genVal.Code = 5;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }


                if (Roles.IsUserInRole("Admin"))
                {
                    genVal.Code = -5;
                }
                else
                {
                    genVal.Code = -2;
                }
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        private List<FieldQuery> GetFieldQueries()
        {
            var previousQueries = new FieldQueryBuilderServices().GetAllOrderedFieldQueries() ?? new List<FieldQuery>();

            if (!previousQueries.Any())
            {
                return new List<FieldQuery>();
            }
            return previousQueries;
        }
    }
}

DPR-DataMigrationEngine/Controllers/WellManagement/WellController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DPR_DataMigrationEngine.BulkUploadManagerManager;
using DPR_DataMigrationEngine.EF.CustomizedModels;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.WellManagement
{
     [CustomAuthorize]
    public class WellController : Controller     
    {
        public WellController()
		{
			 ViewBag.LoadStatus = "0";
		}
        private const int ItemsPerPage = 50;
        private const int PageNumber = 1;

         [CustomAuthorize(Roles = "Admin")]
        public ActionResult Wells()
        {
             try
            {
               var wellTypeList = GetWellTypes();

                if (!wellTypeList.Any())
                {
                    return RedirectToAction("WellTypes", "WellType");
                }

                var fieldList = GetFields();

                if (!fieldList.Any())
                {
                    return RedirectToAction("Fields", "Field");
                }

                var wellClassList = GetWellClasses();
                if (!wellClassList.Any())
                {
                    return RedirectToAction("WellClasses", "WellClass");
                }

                int dataCount;
                var wellList = GetWells(ItemsPerPage, PageNumber, out dataCount);

                if (!wellList.Any())
                {
                    ViewBag.ErrorCode = 0;
                    ViewBag.Title = "Well SetUp";
                    return View(new WellViewModel
                    {
                        WellTypes = wellTypeList,
                        Fields = fieldList,
                        Blocks = GetBlocks(),
                        Wells = wellList,
                        WellClasses = wellClassList
                    });

                }

                ViewBag.Title = "Manage Wells";
                Session["_wellPage"] = 1;
                return View(new WellViewModel { WellTypes = wellTypeList, Fields = fieldList, Blocks = GetBlocks(), Wells = wellList, WellClasses = wellClassList });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorCode = -1;
                ViewBag.ErrorMessage = "Well list could not be retrieved. Please try again or contact the Admin.";
                ViewBag.Title = "Well SetUp";
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return View(new WellViewModel { WellTypes = GetWellTypes(), Fields = GetFields(), Blocks = GetBlocks(), Wells = new List<Well>(), WellClasses = GetWellClasses() });
            }
        }

         public ActionResult GetMoreWells()  
         {
             int currentPage;
             
             var o = Session["_wellPage"];
             if (o != null)
             {
                 var page = (int)o;
                 if (page < 1)
                 {
                     currentPage = 1;
                 }

                 else
                 {
                     currentPage = page + 1;
                 }
             }
             else
             {
                 currentPage = 1;
             }

             var wellList = GetMoreWellObjects(50, currentPage);

             if (!wellList.Any())
             {
                 return Json(new List<Company>(), JsonRequestBehavior.AllowGet);
             }
             Session["_wellPage"] = currentPage;
             return Json(wellList, JsonRequestBehavior.AllowGet);
         }

         private List<WellReportObject> GetMoreWellObjects(int itemsPerPage, int pageNumber)
         {
             try
             {
                 var wellList = new WellServices().GetWellObjects(itemsPerPage, pageNumber) ?? new List<WellReportObject>();

                 if (!wellList.Any())
                 {
                     return new List<WellReportObject>();
                 }

                 return wellList;
             }
             catch (Exception ex)
             {
                 ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                 return new List<WellReportObject>();
             }
         }

         private List<WellReportObject> GetWellObjects(int itemsPerPage, int pageNumber, long companyId)
         {
             try
             {
                 var wellList = new WellServices().GetWellObjects(itemsPerPage, pageNumber, companyId) ?? new List<WellReportObject>();

                 if (!wellList.Any())
                 {
                     return new List<WellReportObject>();
                 }
                 
                 return wellList;
             }
             catch (Exception ex)
             {
                 ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                 return new List<WellReportObject>();
             }
         }

         private List<WellType> GetWellTypes()
        {
            var wellTypeList = new WellTypeServices().GetAllOrderedWellTypes() ?? new List<WellType>();

            if (!wellTypeList.Any())
            {
                return new List<WellType>();
            }

            return wellTypeList;
        }

        private ActionResult GetSelect2Wells()
        {
            try
            {
                var fxs = new WellServices().GetWells() ?? new List<Well>();
                if (!fxs.Any())
                {
                    return Json(new List<Well>(), JsonRequestBehavior.AllowGet);
                }

                return Json(fxs, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
               
                ErrorLogger.LogEror(ex.StackTrace,ex.Source,ex.Message);
                return Json(new List<Well>(), JsonRequestBehavior.AllowGet);
            }
        }

        private List<Well> GetWells(int itemsPerPage, int pageNumber, out int dataCount)
        {
            try
            {
                var fxs = new WellServices().GetAllOrderedWells(itemsPerPage, pageNumber, out dataCount) ?? new List<Well>();
                if (!fxs.Any())
                {
                    return new List<Well>();
                }
                dataCount = dataCount - 1;
                ViewBag.DataCount = dataCount.ToString(CultureInfo.InvariantCulture);

                var totalPages = dataCount / itemsPerPage;

                // Counting the last page
                if (dataCount % itemsPerPage != 0)
                {
                    totalPages++;
                }
                fxs.Remove(fxs.Find(m => m.WellId == (int)OtherNotAvailable.Not_Available));
                //ViewBag.ItemCount = (pageNumber * itemsPerPage) - 150;

                ViewBag.TotalPages = totalPages;
                ViewBag.Page = pageNumber;
                return fxs;
            }
            catch (Exception ex)
            {
                dataCount = 0;
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                return new List<Well>();
            }
        }
        private List<WellClass> GetWellClasses()
        {
            var wellTypeList = new WellClasServices().GetAllOrderedWellClasses2() ?? new List<WellClass>();

            if (!wellTypeList.Any())
            {
                return new List<WellClass>();
            }

            return wellTypeList;
        }

        private List<Company> GetCompanies()
        {
            var companyList = new CompanyServices().GetCompaniesWithFields() ?? new List<Company>();

            if (!companyList.Any())
            {
                return new List<Company>();
            }

            return companyList;
        }
        private List<Field> GetFields()
        {
            var fielList = new FieldServices().GetFields() ?? new List<Field>();

            if (!fielList.Any())
            {
                return new List<Field>();
            }

            return fielList;
        }

        public ActionResult GetFieldsByBlock(int blockId) 
        {  
            try
            {
                if (blockId < 1)
                {
                    return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
                }

                var blocklist = new FieldServices().GetFieldsByBlockId(blockId);

                if (!blocklist.Any())
                {
                    return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
                }

                return Json(blocklist, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetBlocksByCompany(long companyId) 
        {
            try
            {
                if (companyId < 1)
                {
                    return Json(new List<BlockObject>(), JsonRequestBehavior.AllowGet);
                }

                var blocklist = new BlockServices().GetCompanyBlocksWithFields(companyId);

                if (!blocklist.Any())
                {
                    return Json(new List<BlockObject>(), JsonRequestBehavior.AllowGet);
                }

                return Json(blocklist, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new List<BlockObject>(), JsonRequestBehavior.AllowGet);
            }
        }

         [CustomAuthorize(Roles = "Admin")]
        [HttpPost]
        public ActionResult AddWell(Well well)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (!ModelState.IsValid)
                {

DPR-DataMigrationEngine/Views/Well/Report.cshtml
@using System.Globalization
@using DPR_DataMigrationEngine.HTMLExtensionHelpers
@model DPR_DataMigrationEngine.ViewModels.WellViewModel
@{
    ViewBag.Title = "Report";
}
<form style="width: 100%" method="POST" id="productionRepoFrm" action="@Url.Action("GetWellReportsByCompany", "Well")">
    <table style="width: 100%">
        <tr>
            <td colspan="3">
              <label style="font-weight: normal; font-size: 10pt; float: left; width: 100%; ">Retrieve Well Reports by Company:</label>
            </td>
        </tr>
        <tr>
            <td class="form-group" style="width: 35%">
                <div style="margin-left: 2%"><i style="width: auto">Company: </i> </div>
                <select class="form-control" name="companyId" id="ddlWellCompRepo">
                    @{
                        var yearExtensions = new ExtensionHelpers().ListOption(Model.Companies, "CompanyId", "Name", "-- Select Company --");

                        foreach (var year in yearExtensions.Select(yearString => Html.Raw(yearString)))
                        {
                            @year
                        }
                    }
                </select>
            </td>
            <td style="width: 20%">
                <div>&nbsp;</div>
                <input type="submit" name="searchDate" class="btn large btnSearch" onclick="return verifyCompletionRepoSearchMonth()" style="width: 130px; border: 1px solid green; float: left" value="Search" />
            </td>
            <td style="width: 20%"></td>
            <td style="padding-right:0; width: 5%">
                <div>&nbsp;</div><div>&nbsp;</div>
                <a onclick="tableToExcel('tblStatWellReport', 'Well Report')"><img src="/Images/export2Excel2.jpg" style="float: right; margin-right: -2%; cursor: pointer" title="Export to Excel" alt="Export to Excel" /></a>
            </td>
            <td style="width: 10%">
                <div>&nbsp;</div><div>&nbsp;</div>
                <img src="/Images/printer-24_opt.png" style="float: left; cursor: pointer; padding-bottom: 7px" alt="Print Report" title="Print Report" onclick="printWellStatReport()" />
            </td>
        </tr>
    </table>
</form>

  <div style="width: 100%" id="dvWellStaticRep">
    <fieldset id="fsWellList" style="background: whitesmoke; width: 100%" class="allcontent">
        <legend class="customlegend22" id="lgHeader">Well Report</legend>
        <table id="tblStatWellReport" style="width: 100%" class="fils-border newTable">
            <tr class="customGridHeader">
                <th style="width: 5%; text-align: center">
                    S/N
                </th>
                <th style="width: 17%; text-align: left">
                    Well
                </th>
                <th style="width: 10%; text-align: left">
                    Well Type
                </th>
                <th style="width: 10%; text-align: left">
                    Well Class
                </th>
                <th style="width: 15%; text-align: left">
                    Company
                </th>
                <th style="width: 10%; text-align: left">
                    Field
                </th>
                <th style="width: 10%; text-align: left">
                    Terrain
                </th>
                <th style="width: 10%; text-align: left">
                    Zone
                </th>
                <th style="width: 10%; text-align: left">
                    Total Dept(FT)
                </th>
                <th style="width: 15%; text-align: left">
                    Technical Allowable(FT)
                </th>
                <th style="width: 10%; text-align: left">
                    Spud Date
                </th>
            </tr>
            @{
                for (var i = 0; i < Model.WellReportObjects.Count(); i++)
                {
                    var zxz = Model.WellReportObjects[i];
                    <tr id="tr@(zxz.WellId)" class="xtcR" style="color: black;">
                        <td style="width: 5%; text-align: center" class="xtc">
                            @(i + 1)
                        </td>
                        <td style="width: 17%; text-align: left" id="tdName">
                            @zxz.Name
                        </td>
                        <td style="width: 10%; text-align: left" id="tdWellType">
                            @zxz.WellTypeName
                        </td>
                        <td style="width: 10%; text-align: left" id="tdWellType">
                            @zxz.WellClassName
                        </td>
                        <td style="width: 15%; text-align: left" id="tdCompany">
                            @zxz.CompanyName
                        </td>
                        <td style="width: 10%; text-align: left" id="tdWellField">
                            @zxz.FieldName
                        </td>
                        <td style="width: 10%; text-align: left">
                            @zxz.TerrainName
                        </td>
                        <td style="width: 10%; text-align: left">
                            @zxz.ZoneName 
                        </td>
                        <td style="width: 10%; text-align: left" id="tdTotalDept">
                            @zxz.TotalDept
                        </td>
                        <td style="width: 15%; text-align: left" id="tdTechValue">
                            @zxz.TechnicalAllowable
                        </td>
                        <td style="width: 10%; text-align: left">
                            @zxz.SpudDate
                        </td>
                    </tr>
                }
            
            }
        </table>
    </fieldset>
</div>

<img src="/Images/select2-spinner.gif" id="imgWellRepoSpin" class="spinProgress2" />

<script type="text/javascript">
    function printWellStatReport() {
        if ($('#tblStatWellReport').html() == null)
        {
            alert('Nothing to Print');
            return;
        }
        printReportData('fsWellList');
    }

    $(".page-button").click(function () {
        if (!$(this).hasClass('current')) {

            window.location.href = "http://" +
                window.location.host + window.location.pathname + 
                '?pageNumber=' + $(this).val() + '&itemsPerPage=' + 50;

        }
    });
    

    $(function () {
        $(window).scroll(function () {
            if ($(window).scrollTop() >= $(document).height() - $(window).height() - 180)
            {
                var url = '/Well/GetMoreStaticWellReports';
                $("#imgWellRepoSpin").show();
                $.ajax({
                    url: url,
                    contentType: 'application/json; charset=utf-8',
                    dataType: 'json',
                    type: 'POST',
                    success: function (zxz) {
                        if (zxz === null) {
                            $("#imgWellRepoSpin").hide();
                        } else {
                            $.each(zxz, function (i, r)
                            {
                                refreshWellRepo2(r);
                            });
                            $("#imgWellRepoSpin").hide();
                        }
                    }
                });
            }
        });
    });

    function refreshWellRepo2(r)
    {

        var bv = $('#tblStatWellReport tr').length - 1;

        $("#tblStatWellReport tbody:last").append($(

            '<tr ><td style="width: 5%; text-align: left">' + (bv + 1) + '</td>'
                + '<td style="width: 17%; text-align: left">' + r.Name
            + '</td><td style="width: 10%; text-align: left">' + r.WellTypeName
            + '</td>'
            + '<td style="width: 10%; text-align: left">' + r.WellClassName + '</td>'
             + '<td style="width: 15%; text-align: left">'
            + r.CompanyName + '</td>'
        + '<td style="width: 10%; text-align: left">' + r.FieldName + '</td>'
            + '<td style="width: 10%; text-align: left">' 
            + r.TerrainName
            + '</td><td style="width: 10%; text-align: left">' + r.ZoneName
            + '</td><td style="width: 10%; text-align: left">' + r.TotalDept + ' </td>'
          +' <td style="width: 15%; text-align: left" id="tdTechValue">'
           + r.TechnicalAllowable + ' </td>'
            + '<td style="width: 10%; text-align: left" >' + r.SpudDate
                + '</td></tr>'));

    }

</script>

DPR-DataMigrationEngine/Views/Well/WellUpload.cshtml
@{
    ViewBag.Title = "Well Bulk Upload";
}


<style type="text/css">
    a#ancClose:link, a#ancClose:visited, a#ancClose:active, a#ancClose:hover
     {
        text-decoration: none;
        background: url(/Images/cancel.png) 80px no-repeat green;
        -ms-background-size: 18px 18px;
        background-size: 18px 18px;
        color: #FFF;
        cursor: pointer;
        border: none;
    }
</style>

@{

    if (ViewBag.ErrorCode < 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: black;"> @td </label>

    }

    if (ViewBag.ErrorCode > 0)
    {
        var td = @Html.Raw(ViewBag.ErrorMessage);
        <label style="font-weight: normal; color: green;">@td</label>

    }
}


<table style="width: 50%">
    <tr>
        <td style="width: 90%">
            <form class="fsEdit" method="POST" action="@Url.Action("WellUpload", "Well")" enctype="multipart/form-data" id="frmProcessDocs" style="width: 100%">
                <span class="legend22" style="width: 100%">Well Bulk Upload</span>
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <table style="width: 100%; background: whitesmoke; border: none;margin-top:0">
                    <tr>
                        <td colspan="2">
                            <div style="width: 100%; font-weight: bold; font-size: 8pt; display: none; visibility: visible" class="error label" id="brEdErrorBulk"></div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2" class="form-group">
                            <div>&nbsp;</div>
                            <br /><i style="width: auto">Select Excel Data File *</i>
                            <input id="fldDocument" type="file" name="file" style="width: 100%" />
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <div>&nbsp;</div>
                            <div style="width: 100%;">
                                <div style="text-align: center; float: right; margin-top: 1%">
                                    <a id="ancClose" style="border: none; float:right; width: 110px" class="btn btnClose large" href="/Well/Wells"> Close</a> &nbsp; &nbsp; &nbsp;
                                </div>
                                    <input type="submit" id="btnProcessBulkUpload" class="btn btnUpload large" style=" border: none; float: right; width: 110px" value="Upload" onclick="return valIdateTemplate();" />
                                </div>
                        </td>
                    </tr>
                </table>
            </form> 
        </td>
        <td style="width:10%; padding-right: 8px; vertical-align: top; text-align: center">
            <div style="text-align: center; float: right">
                <a title="Download Bulk Upload Template" style="cursor:pointer" href="@("/Well/DownloadContentFromFolder?path=" + "~/BulkTemplate/WellTemplate.xlsx")"><img src="/Images/downloadExcel.png" alt="download Bulk Upload Template" style="width: 40px; height: 40px" /></a>
            </div>
        </td>
    </tr>
</table>

<script type="text/javascript">
    
    function valIdateTemplate() {
        if ($('#fldDocument').val().trim().length < 1)
        {
            alert("Please Select an Excel file to upload!");
            $('#fldDocument').val('');
            return false;
        }

        //if (!validateTemplate('frmProcessDocs'))
        //{
        //    $('#brEdErrorBulk').text('Validation failed. Please check the input fileds and try again')
        //        .fadeIn();
        //    return false;
        //}
        return true;
        // $('#btnProcessBulkUpload').unbind('click').click();
    }
    

    $('#ddlBulkCompanies').on('change', function ()
    {
        $('#brEdErrorBulk').text('');
        $('#brEdErrorBulk').fadeOut('slow');
        var rxv = parseInt($(this).val());

        if (rxv < 1)
        {
            alert('Invalid selection');
            return;
        }

        var url = '/Well/GetBlocksByField?fieldId=' + rxv;

        $.get(url, function (retVal)
        {
            populateBulkDropdown(retVal);
        });

    });

    function populateBulkDropdown(data)
    {
        if (data == null || data.length < 1)
        {
            $('#brEdErrorBulk').text("Block list for the selected Company could not be retrieved");
            $('#ddlBulkBlocks').html('<option value="0"> -- List is empty -- </option>');
            $('#ddlBulkBlocks').prop('disabled', true);
            $('#brEdErrorBulk').fadeIn('slow');
            return;
        }
        $('#ddlBulkBlocks').empty();
        $('#ddlBulkBlocks').html('<option value="0"> -- Select Block -- </option>');
        $.each(data, function (i, v) {
            if (v.BlockId < 1) {
                $('#ddlBulkBlocks').empty();
                $('#ddlBulkBlocks').html('<option value="0"> -- List is empty -- </option>');
                $('#ddlBulkBlocks').prop('disabled', 'disabled');
                alert('An error was encountered while compiling the Block list. Process has been terminated');
                return;
            }

            $('#ddlBulkBlocks').append($("<option />").val(v.BlockId).text(v.Name));
        });

        $('#ddlBulkBlocks').prop('selectedIndex', 0);
        $('#ddlBulkBlocks').prop('disabled', false);
    }
</script>