DPR-DataMigrationEngine/Controllers/EquipmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.BulkUploadManagerManager;
using DPR_DataMigrationEngine.EF.CustomizedModels;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;

namespace DPR_DataMigrationEngine.Controllers
{
    [CustomAuthorize(Roles = "Admin")]
    public class EquipmentController : Controller
    {
        public EquipmentController()
		{
			 ViewBag.LoadStatus = "0";
		}
        public ActionResult Equipments()
        {
            var equipmentTypeList = new EquipmentTypeServices().GetAllOrderedEquipmentTypes() ?? new List<EquipmentType>();

            if (!equipmentTypeList.Any())
            {

                return RedirectToAction("EquipmentTypes", "EquipmentType");
            }

            var equipmentList = new EquipmentServices().GetAllOrderedEquipments() ?? new List<Equipment>();

            if (!equipmentList.Any())
            {
                ViewBag.Edit = 1;
                ViewBag.Title = "Equipment Type SetUp";
                return View(Tuple.Create(equipmentTypeList, new List<Equipment>()));
            }
            equipmentList.ForEach(m =>
            {
                m.EquipmentLicenseStatus = m.LicenseStatus ? "Licensed" : "Unlicensed";
            });
           
            var txx = Tuple.Create(equipmentTypeList, equipmentList);
            ViewBag.Title = "Manage Equipments";
            return View(txx);
        }

        [HttpPost]
        public ActionResult AddEquipment(Equipment equipment)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (!ModelState.IsValid)
                {
                    equipment.Error = "Please supply all required fields and try again";
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                var wx = ValidateControl(equipment);

                if (wx.Code < 1)
                {
                    equipment.Error = wx.Error;
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }
              
                equipment.EquipmentType = new EquipmentType
                {
                    EquipmentTypeId = equipment.EquipmentTypeId,
                    Name = equipment.EquipmentType.Name
                };
                equipment.EquipmentLicenseStatus = equipment.LicenseStatus ? "Licensed" : "Unlicensed";
                var k = new EquipmentServices().AddEquipmentCheckDuplicate(equipment);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        equipment.Error = "Equipment  already exists";
                        equipment.ErrorCode = -3;
                        return Json(equipment, JsonRequestBehavior.AllowGet);
                    }

                    equipment.Error = "Process Failed! Please contact the Admin or try again later";
                    equipment.ErrorCode = 0;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                equipment.Error = "Record was added successfully";
                equipment.ErrorCode = 1;
                equipment.EquipmentId = k;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                equipment.Error = "An unknown error was encountered. Request could not be serviced. Please try again later.";
                equipment.ErrorCode = 0;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditEquipment(Equipment equipment)
        {
            ModelState.Clear();
            ViewBag.LoadStatus = "0";
            try
            {
                if (Session["_equipment"] == null)
                {
                    equipment.Error = "Session has expired";
                    equipment.ErrorCode = 0;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                var oldEquipment = Session["_equipment"] as Equipment;

                if (oldEquipment == null || oldEquipment.EquipmentId < 1)
                {
                    equipment.Error = "Session has expired";
                    equipment.ErrorCode = 0;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                if (!ModelState.IsValid)
                {
                    equipment.Error = "Please supply all required fields and try again";
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                var wx = ValidateControl(equipment);

                if (wx.Code < 1)
                {
                    equipment.Error = wx.Error;
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                oldEquipment.Name = equipment.Name;
                oldEquipment.EquipmentTypeId = equipment.EquipmentTypeId;
                oldEquipment.LicenseStatus = equipment.LicenseStatus;
                oldEquipment.EquipmentType = new EquipmentType
                {
                    EquipmentTypeId = equipment.EquipmentTypeId,
                    Name = equipment.EquipmentType.Name
                };
                equipment.EquipmentLicenseStatus = equipment.LicenseStatus ? "Licensed" : "Unlicensed";
                var k = new EquipmentServices().UpdateEquipmentCheckDuplicate(oldEquipment);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        equipment.Error = "Equipment  already exists";
                        equipment.ErrorCode = 0;
                        return Json(equipment, JsonRequestBehavior.AllowGet);
                    }

                    equipment.Error = "Process Failed! Please contact the Admin or try again later";
                    equipment.ErrorCode = 0;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }
                
                    equipment.Error = "Equipment  Information was successfully updated";
                    equipment.ErrorCode = 1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
              
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                equipment.Error = "An unknown error was encountered. Request could not be serviced. Please try again later.";
                equipment.ErrorCode = 0;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ActionName("DeleteEquipment")]
        public ActionResult DeleteEquipment(int id)
        {
            var equipment = new Equipment();

            try
            {
                if (id < 1)
                {
                    equipment.Error = "Invalid Selection";
                    equipment.ErrorCode = 0;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }
                if (new EquipmentServices().DeleteEquipmentCheckReferences(id))
                {
                    equipment.Error = "Equipment  Information was successfully deleted.";
                    equipment.ErrorCode = 1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                equipment.Error = "Process Failed! Please try again later";
                equipment.ErrorCode = 0;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                equipment.Error = "An unknown error was encountered. Please contact the Administrator or try again later.";
                equipment.ErrorCode = 0;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult EditEquipment(int id)
        {
            var equipment = new Equipment();
            try
            {
                if (id < 1)
                {
                    equipment.Error = "Invalid Selection!";
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }

                var myViewObj = new EquipmentServices().GetEquipment(id);

                if (myViewObj == null || myViewObj.EquipmentId < 1)
                {
                    equipment.Error = "Equipment  Information could not be retrieved.";
                    equipment.ErrorCode = -1;
                    return Json(equipment, JsonRequestBehavior.AllowGet);
                }
                Session["_equipment"] = myViewObj;
                myViewObj.ErrorCode = myViewObj.EquipmentId;
                return Json(myViewObj, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                ErrorLogger.LogEror(ex.StackTrace, ex.Source, ex.Message);
                equipment.Error = "An unknown error was Equipment  Information could not be retrieved.";
                equipment.ErrorCode = -1;
                return Json(equipment, JsonRequestBehavior.AllowGet);
            }
        }

        private static GenericValidator ValidateControl(Equipment model)
        {
            var gVal = new GenericValidator();

DPR-DataMigrationEngine/Controllers/Reports/DynamicReports/FieldReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using DPR_DataMigrationEngine.EF.Models;
using DPR_DataMigrationEngine.GenericHelpers;
using DPR_DataMigrationEngine.Services.ServiceManager;
using DPR_DataMigrationEngine.ViewModels;

namespace DPR_DataMigrationEngine.Controllers.Reports.DynamicReports
{
    [CustomAuthorize]
    public class FieldReportController : Controller
    {
       public ActionResult DynamicReports()
        {
            return View(new FieldViewModel
            {
                Terrains = GetTerrains(),
                Zones = GetZones(),
                Companies = GetCompanyies(), 
                FieldQueries = GetFieldQueries() });
        }

       private List<Terrain> GetTerrains()
       {
           return new TerrainServices().GetAllOrderedTerrains() ?? new List<Terrain>();
       }
        private List<BlockType> GetBlockTypes()
        {
            return new BlockTypeTypeServices().GetAllOrderedBlockTypes() ?? new List<BlockType>();
        }
        private List<Block> GetBlocks()
        {
            return new BlockServices().GetAllOrderedBlocks() ?? new List<Block>();
        }
        private List<Company> GetCompanyies()
        {
            return new CompanyServices().GetCompaniesWithBlocks() ?? new List<Company>();
        }
        private List<Zone> GetZones()
        {
            return new ZoneServices().GetAllOrderedZones() ?? new List<Zone>();
        }
        public ActionResult GetFields(FieldQuery queryBuilder)
        {
            if (queryBuilder == null)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            
            if (queryBuilder.TerrainId < 1 && queryBuilder.CompanyId < 1 && queryBuilder.ZoneId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(queryBuilder) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }
            Session["_successfulFieldQuery"] = queryBuilder;
            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        public ActionResult GetFields2(int queryId)
        {
            if (queryId < 1)
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var query = new FieldQueryBuilderServices().GetFieldQuery(queryId);

            if (query == null || query.FieldQueryId < 1)
            {

                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var fieldList = new FieldServices().GetOrderedFieldReportObjects(query) ?? new List<FieldReportObject>();

            if (!fieldList.Any())
            {
                return Json(new List<FieldReportObject>(), JsonRequestBehavior.AllowGet);
            }

            var jsonResult = Json(fieldList, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;

        }
        [HttpPost]
        public ActionResult SaveSuccessfulQuery(string queryName)
        {
            var genVal = new GenericValidator();

            try
            {
                if (string.IsNullOrEmpty(queryName))
                {
                    genVal.Error = "Please supply all required fields and try again";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Error = "Session has expired";
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                queryBuilder.FieldQueryName = queryName.Trim();

                var k = new FieldQueryBuilderServices().AddFieldQueryCheckDuplicate(queryBuilder);
                if (k < 1)
                {
                    if (k == -3)
                    {
                        genVal.Error = "Query already exists";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }
                    if (k == -4)
                    {
                        genVal.Error = "Query Name already exists. Please provide a different one";
                        genVal.Code = -3;
                        return Json(genVal, JsonRequestBehavior.AllowGet);
                    }

                    genVal.Error = "Process Failed! Please contact the Admin or try again later";
                    genVal.Code = 0;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                genVal.Error = "Query was successfully saved";
                genVal.Code = (int) k;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                //ErrorManager.LogApplicationError(ex.StackTrace, ex.Source, ex.Message);
                genVal.Error = "An unknown error was encountered. Query could not be saved. Please try again.";
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult IsFieldQueryExisting()
        {
            var genVal = new GenericValidator();

            try
            {
                if (Session["_successfulFieldQuery"] == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var queryBuilder = Session["_successfulFieldQuery"] as FieldQuery;

                if (queryBuilder == null)
                {
                    genVal.Code = -1;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }

                var k = new FieldQueryBuilderServices().IsFieldQueryExisting(queryBuilder);
                if (k)
                {
                    genVal.Code = 5;
                    return Json(genVal, JsonRequestBehavior.AllowGet);
                }


                if (Roles.IsUserInRole("Admin"))
                {
                    genVal.Code = -5;
                }
                else
                {
                    genVal.Code = -2;
                }
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                genVal.Code = 0;
                return Json(genVal, JsonRequestBehavior.AllowGet);
            }
        }
        private List<FieldQuery> GetFieldQueries()
        {
            var previousQueries = new FieldQueryBuilderServices().GetAllOrderedFieldQueries() ?? new List<FieldQuery>();

            if (!previousQueries.Any())
            {
                return new List<FieldQuery>();
            }
            return previousQueries;
        }
    }
}

DPR-DataMigrationEngine/Views/Equipment/Equipments.cshtml
@using DPR_DataMigrationEngine.HTMLExtensionHelpers
@model Tuple<List<DPR_DataMigrationEngine.EF.Models.EquipmentType>, List<DPR_DataMigrationEngine.EF.Models.Equipment>>

<form action="@Url.Action("AddEquipment", "Equipment")" id="fsProcessEquipments" class="fsEdit" style="display: none; visibility: visible">
    <span class="legend22" id="lgEditEquipment" style="width: 100%">Add New Equipment Type</span>

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <table style="width: 100%; border: none">
        <tr>
            <td>
                <div style="width: 100%; font-weight: bold; font-size: 8pt; display: none; visibility: visible" class="error label" id="brEdErrorEquipment"></div>
            </td>
        </tr>
        <tr>
            <td class="form-group">
                <div>&nbsp;</div>
                <div style="margin-left: 2%"><i style="width: auto">Equipment</i><span style="color: red">*</span><span class="field-validation-valid" id="sptxtEquipmentName" data-valmsg-for="branch.Name" style="color: red" data-valmsg-replace="true">Required</span></div>
                <input type="text" name="equipment.Name" id="txtEquipmentName" class="form-control" style="margin-left: 2%" />
            </td>
        </tr>
        <tr>
            <td class="form-group">
                <div style="margin-left: 2%"><i style="width: auto">Equipment Type</i><span style="color: red">*</span><span class="field-validation-valid" id="spddlEquipmentTypes" data-valmsg-for="branch.CountryId" style="color: red" data-valmsg-replace="true">Invalid Selection</span> </div>
                <select class="form-control" style="height: 34px" name="equipment.EquipmentTypeId" id="ddlEquipmentTypes">
                    @{
                        var fr = new ExtensionHelpers().ListOption(Model.Item1, "EquipmentTypeId", "Name", "-- Select Equipment Type --");

                        foreach (var yf in fr.Select(dc => Html.Raw(dc))) 
                        {
                            @yf
                        }

                    }
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <input type="checkbox" id="chkLicenseStatus" name="equipment.LicenseStatus" style="margin-left: 2%" />&nbsp; Licensed?&nbsp;&nbsp;&nbsp;
            </td>
        </tr>
        <tr>
            <td>
                <div style="width: 100%; margin-left: 0"> 
                    <input type="button" id="btnCloseProcessEquipment" style="border: none; float:right; width: 110px" class="btn btnClose large" value="Close" />&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <input type="submit" id="btnProcessEquipment" class="btn btnSave large" style=" border: none; float: right; width: 110px" value="Submit" />
                </div>
            </td>
        </tr>
    </table>
</form>

<fieldset id="fsEquipmentList" style="background: whitesmoke; width: 100%" class="allcontent">
    <legend class="customlegend22" id="lgHeader">@ViewBag.Title</legend>
    <label id="brProcess" style="display: none; visibility: visible"></label>
    <table style="width: 100%; background: whitesmoke; border: 1px solid gainsboro; top: 10%">
        <tr>
            <td style="width: 80%">
                <div style="width: 100%; font-weight: bold; font-size: 9pt; display: none; visibility: visible" id="brFeedbackEquipment"></div>
            </td>
            <td style="width: 20%">
                <div style="width: 100%">
                    <input type="button" id="btnAddNewCompanyEquipment" onclick="prepareEquipmentTemplate()" value="New Equipment Type" class="btn btnAdd large" style="width: 190px; float: right" />
                </div>
            </td>
        </tr>
    </table>
    <table id="tblEquipments" style="width: 100%" class="fils-border newTable"> 
        <tr class="customGridHeader">
            <th style="width: 3%; text-align: center">
                S/N
            </th>
            <th style="width: 29%; text-align: left">
                Equipment
            </th>
            <th style="width: 29%; text-align: left">
                Equipment Type
            </th>
            <th style="width: 29%; text-align: left">
               License Status
            </th>
            <th style="width: 10%">
                Action
            </th>
        </tr>
        @{
            for (var i = 0; i < Model.Item2.Count(); i++)
            {
                var zxz = Model.Item2[i];
                <tr id="tr@(zxz.EquipmentId)" class="xtcR" style="color: black;">
                    <td style="width: 3%; text-align: center" class="xtc">
                        @(i + 1)
                    </td>
                    <td style="width: 29%; text-align: left" id="tdName">
                        @zxz.Name
                    </td>
                    <td style="width: 29%; text-align: left" id="tdType">
                        @zxz.EquipmentType.Name
                    </td>
                    <td style="width: 29%; text-align: left" id="tdLicenseStatus"> 
                       @zxz.EquipmentLicenseStatus
                    </td>
                    <td style="width: 10%">
                        <a class="equipmentEdTx" title="Edit" id="ed@(zxz.EquipmentId)" onclick="equipmentEdTx(this.id);"><img src="/Images/edit.png" alt="Edit" /></a>&nbsp;&nbsp;<a class="equipmentDeltx" title="Delete" id="del@(zxz.EquipmentId)" onclick="equipmentDeltx(this.id);"><img src="/Images/delete_opt(1).png" alt="Delete" /></a>
                    </td>
                </tr>
            }
        }
    </table>
</fieldset>

<script type="text/javascript">

    $(window).load(function ()
    {
    });
    
    function feedBackStatus(x, z)
    {
        var dx = parseInt(x);

        if (dx === 0 || dx === 2 || dx === -3)
        {
            $("#brFeedbackEquipment").text(z);
            $("#brFeedbackEquipment").removeClass('success');
            $("#brFeedbackEquipment").addClass('error');
            $("#brFeedbackEquipment").fadeIn();
        }

        if (dx === 1)
        {
            $("#brFeedbackEquipment").text(z);
            $("#brFeedbackEquipment").removeClass('error');
            $("#brFeedbackEquipment").addClass('success');
            $("#brFeedbackEquipment").fadeIn();
        }
    }

    $(document).ready(function ()
    {
        toggleValidators('fsProcessEquipments');


        $('.equipmentDeltx').on("click", function ()
        {
            $("#brFeedbackEquipment").fadeOut();
            
        });

        $('#btnCloseProcessEquipment').on("click", function ()
        {
            $("#brFeedbackEquipment").fadeOut();
            closePopModal($('#fsProcessEquipments'));
            $('#brEdErrorEquipment').text('');
            $('#brEdErrorEquipment').hide();
        });

        $("#fsProcessEquipments").submit(function (e) {
            $("#brFeedbackEquipment").fadeOut();
            e.preventDefault();

            if (!validateTemplate('fsProcessEquipments')) {
                return;
            }

            var vx = $('#txtEquipmentName');
            var rx = $('#chkLicenseStatus');
            var rnx = $('#ddlEquipmentTypes');

            var newEquipment = {};
            newEquipment.EquipmentId = rtx;
            
            newEquipment['Name'] = vx.val();
            
            if (rx.is(':checked'))
            {
                newEquipment['LicenseStatus'] = 'true';
            } else
            {
                newEquipment['LicenseStatus'] = 'false';
            }
            newEquipment['EquipmentTypeId'] = rnx.val();
            newEquipment.EquipmentType = {};
            newEquipment.EquipmentType.Name = $("#ddlEquipmentTypes option:selected").text();

            var sdx = JSON.stringify({ equipment: newEquipment });
            var url = $(this).attr('action');
            $.ajax({
                url: url,
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                data: sdx,
                type: 'POST',
                success: function (zxz)
                {
                    if (zxz.ErrorCode === -1 || zxz.ErrorCode === -2 || zxz.ErrorCode === 0 || zxz.ErrorCode === -3)
                    {
                        $('#brEdErrorEquipment').text(zxz.Error);
                        $('#brEdErrorEquipment').fadeIn('slow');
                        return;
                    }

                    if ($('#brProcess').text() === "1")
                    {
                        refresh(zxz);
                    }

                    if ($('#brProcess').text() === "2")
                    {
                        updateTable(zxz);
                    }
                    
                    $('#brEdErrorEquipment').text('');
                    $('#brEdErrorEquipment').hide();
                }
            });
        });
    });


    var rtx = 0;
    function equipmentEdTx(x)
    {
        $('#brProcess').text('');
        $("#brFeedbackEquipment").fadeOut();
        var xxid = parseInt(x.replace('ed', ''));
        if (xxid < 1)
        {
            alert("Invalid Selection!");
            return;
        }
        rtx = xxid;
        var url = '/Equipment/EditEquipment?id=' + xxid;

        $.get(url, function (data)
        {
             edGet(data);
        });

    }

    function edGet(data)
    {
        if (data.ErrorCode < 1)
        {
            //Data could not be retrieved/Database operation failed/An unknown error was encountered
            feedBackStatus(data.ErrorCode, data.Error);
            return;
        }

        refreshForm('fsProcessEquipments', 'Update');
        $('#fsProcessEquipments').attr("action", "/Equipment/EditEquipment");
        $('#txtEquipmentName').val(data.Name);
        
        if (data.LicenseStatus === true)
        {
            $('#chkLicenseStatus').prop('checked', true);
        }
        $('#ddlEquipmentTypes').val(data.EquipmentTypeId);
        $('#lgEditEquipment').text('Update Equipment');
        $('#brProcess').text(2);
        setModal($('#fsProcessEquipments'));
    }

    function equipmentDeltx(x) {

        var xxid = parseInt(x.replace('del', ''));
        if (xxid < 1) {
            alert("Invalid Selection!");
            return;
        }

        $.ajax({
            beforeSend: function () { return confirm('Are you sure you want to delete this item?'); },
            url: "/Equipment/DeleteEquipment?id=" + xxid,
            type: 'POST',
            success: function (i) {
                if (i.ErrorCode < 1) {
                    ///Database operation failed/Data could not be deleted
                    feedBackStatus(i.ErrorCode, i.Error);
                    return;
                }

                $('#tblEquipments #tr' + xxid).remove();

                $('#tblEquipments tr.xtcR').each(function (r)
                {
                    $(this).children('.xtc').text(r + 1);
                });
                $('#tblEquipments .xtcR:even').addClass('gridItem1');
            }
        });
        return;
    }

    function prepareEquipmentTemplate()
    {
        $('#brEdErrorEquipment').text('');
        $('#brEdErrorEquipment').hide();
        refreshForm('fsProcessEquipments', '');
        $('#fsProcessEquipments').attr("action", "/Equipment/AddEquipment");
        $('#brProcess').text(1);
        setModal($('#fsProcessEquipments'));
    }
  
    function updateTable(r)
    {
        $('#tblEquipments #tr' + rtx).children('#tdName').html(r.Name);
        $('#tblEquipments #tr' + rtx).children('#tdType').html(r.EquipmentType.Name);
        $('#tblEquipments #tr' + rtx).children('#tdLicenseStatus').html(r.EquipmentLicenseStatus);

        //$('#tblEquipments .xtcR:even').addClass('gridItem1');
        //Successfull operation
        feedBackStatus(r.ErrorCode, r.Error);
        $('#brProcess').text(0);
        closePopModal($('#fsProcessEquipments'));
    }

    function refresh(r)
    {
        var bv = $('#tblEquipments tr').length - 1;
        
        $("#tblEquipments tbody:last").append($('<tr class="xtcR" id="tr' + r.EquipmentId + '"><td style="width: 7%;text-align: center" class="xtc">' + (bv + 1) + '</td><td style="width: 29%; text-align: left" id="tdName">' + r.Name + '</td><td style="width: 29%; text-align: left" id="tdType">' + r.EquipmentType.Name + '</td><td style="width: 29%; text-align: left" id="tdLicenseStatus">' + r.EquipmentLicenseStatus + '</td><td style="width: 10%"><a class="equipmentEdTx" title="Edit" id="ed' + r.EquipmentId + '"  onclick="equipmentEdTx(this.id);">><img src="/Images/edit.png" style="cursor: pointer" alt ="Edit"/></a>&nbsp;&nbsp;<a class="equipmentDeltx" title="Delete" id="del' + r.EquipmentId + '" onclick="equipmentDeltx(this.id);"><img src="/Images/delete_opt(1).png" alt="Delete" style="cursor: pointer"/></a></td></tr>'));

        //Successfull operation
        $('#tblEquipments .xtcR:even').addClass('gridItem1');
        $('#brProcess').text(0);
        feedBackStatus(r.ErrorCode, r.Error);
        closePopModal($('#fsProcessEquipments'));
    }
</script>